//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOPACE_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class buku_rekening
    {
        public string id_req { get; set; }
        public string keperluan { get; set; }
        public string nama_bank { get; set; }
    
        public virtual request request { get; set; }
    }
}
