//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOPACE_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class file_dokumen
    {
        public string id_dok { get; set; }
        public string NIP { get; set; }
        public string foto_profil { get; set; }
        public string foto_buku_rekening { get; set; }
        public string cv { get; set; }
    
        public virtual personal_information personal_information { get; set; }
    }
}
