//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOPACE_MVC.Models
{
    using System;
    using System.Collections.Generic;

    public partial class lembur
    {
        public string id_lembur { get; set; }
        public string NIP { get; set; }
        public Nullable<System.DateTime> tanggal { get; set; }
        public Nullable<System.TimeSpan> jam_mulai { get; set; }
        public Nullable<System.TimeSpan> jam_selesai { get; set; }
        public Nullable<System.TimeSpan> total_jam { get; set; }
        public string alasan { get; set; }
        public string stats { get; set; }
        public string keterangan { get; set; }

        public virtual personal_information personal_information { get; set; }


    }
}
