//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOPACE_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notifikasi
    {
        public string id_req { get; set; }
        public string id_notifikasi { get; set; }
        public string id_penerima { get; set; }
        public string status { get; set; }
    }
}
