//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOPACE_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personal_information
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personal_information()
        {
            this.cutis = new HashSet<cuti>();
            this.file_dokumen = new HashSet<file_dokumen>();
            this.klaim_medis = new HashSet<klaim_medis>();
            this.lemburs = new HashSet<lembur>();
            this.requests = new HashSet<request>();
            this.users = new HashSet<user>();
        }
    
        public string NIP { get; set; }
        public string nama_pegawai { get; set; }
        public Nullable<System.DateTime> tgl_lahir { get; set; }
        public string alamat_identitas { get; set; }
        public string alamat_domisili { get; set; }
        public string NPWP { get; set; }
        public string no_ktp { get; set; }
        public string no_hp { get; set; }
        public string agama { get; set; }
        public string email { get; set; }
        public string pendidikan { get; set; }
        public string jurusan { get; set; }
        public Nullable<System.DateTime> tgl_masuk { get; set; }
        public string status_pajak { get; set; }
        public string jenis_kelamin { get; set; }
        public string status_aktif { get; set; }
        public string no_rek { get; set; }
        public string penempatan { get; set; }
        public string posisi { get; set; }
        public Nullable<System.DateTime> tgl_resign { get; set; }
        public string alasan_resign { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cuti> cutis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<file_dokumen> file_dokumen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<klaim_medis> klaim_medis { get; set; }
        public virtual kuota_cuti kuota_cuti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lembur> lemburs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<request> requests { get; set; }
        public virtual tunjangan_medical tunjangan_medical { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> users { get; set; }
    }
}
