//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOPACE_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        public string id_req { get; set; }
        public string NIP { get; set; }
        public string nama_pegawai { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> tanggal_request { get; set; }
    
        public virtual buku_rekening buku_rekening { get; set; }
        public virtual keterangan_kerja keterangan_kerja { get; set; }
        public virtual NPWP NPWP { get; set; }
        public virtual pemberitahuan pemberitahuan { get; set; }
        public virtual personal_information personal_information { get; set; }
        public virtual slip_gaji slip_gaji { get; set; }
        public virtual visa visa { get; set; }
    }
}
