//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOPACE_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ACEEntities : DbContext
    {
        public ACEEntities()
            : base("name=ACEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<buku_rekening> buku_rekening { get; set; }
        public virtual DbSet<cuti> cutis { get; set; }
        public virtual DbSet<file_dokumen> file_dokumen { get; set; }
        public virtual DbSet<keterangan_kerja> keterangan_kerja { get; set; }
        public virtual DbSet<klaim_medis> klaim_medis { get; set; }
        public virtual DbSet<kuota_cuti> kuota_cuti { get; set; }
        public virtual DbSet<lembur> lemburs { get; set; }
        public virtual DbSet<notifikasi> notifikasis { get; set; }
        public virtual DbSet<NPWP> NPWPs { get; set; }
        public virtual DbSet<pemberitahuan> pemberitahuans { get; set; }
        public virtual DbSet<personal_information> personal_information { get; set; }
        public virtual DbSet<request> requests { get; set; }
        public virtual DbSet<slip_gaji> slip_gaji { get; set; }
        public virtual DbSet<tunjangan_medical> tunjangan_medical { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<visa> visas { get; set; }
    
        [DbFunction("ACEEntities", "fn_getLastNIP")]
        public virtual IQueryable<fn_getLastNIP_Result> fn_getLastNIP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_getLastNIP_Result>("[ACEEntities].[fn_getLastNIP]()");
        }
    
        public virtual ObjectResult<string> pr_CekLogin(string usrnm, string pwd)
        {
            var usrnmParameter = usrnm != null ?
                new ObjectParameter("usrnm", usrnm) :
                new ObjectParameter("usrnm", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("pr_CekLogin", usrnmParameter, pwdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pr_cekNipAlready(string cekNip)
        {
            var cekNipParameter = cekNip != null ?
                new ObjectParameter("CekNip", cekNip) :
                new ObjectParameter("CekNip", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pr_cekNipAlready", cekNipParameter);
        }
    
        public virtual int pr_cekPassword(string cekPwd, ObjectParameter retPwd)
        {
            var cekPwdParameter = cekPwd != null ?
                new ObjectParameter("cekPwd", cekPwd) :
                new ObjectParameter("cekPwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_cekPassword", cekPwdParameter, retPwd);
        }
    
        public virtual int pr_cekUsername(string cekUsername, ObjectParameter retUsrnm)
        {
            var cekUsernameParameter = cekUsername != null ?
                new ObjectParameter("cekUsername", cekUsername) :
                new ObjectParameter("cekUsername", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_cekUsername", cekUsernameParameter, retUsrnm);
        }
    
        public virtual ObjectResult<string> pr_createSU(string password)
        {
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("pr_createSU", passwordParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pr_DiffKuotaCuti(string nip, Nullable<System.DateTime> dateawal, Nullable<System.DateTime> dateakhir, Nullable<int> jmlh_LbrNas)
        {
            var nipParameter = nip != null ?
                new ObjectParameter("nip", nip) :
                new ObjectParameter("nip", typeof(string));
    
            var dateawalParameter = dateawal.HasValue ?
                new ObjectParameter("dateawal", dateawal) :
                new ObjectParameter("dateawal", typeof(System.DateTime));
    
            var dateakhirParameter = dateakhir.HasValue ?
                new ObjectParameter("dateakhir", dateakhir) :
                new ObjectParameter("dateakhir", typeof(System.DateTime));
    
            var jmlh_LbrNasParameter = jmlh_LbrNas.HasValue ?
                new ObjectParameter("Jmlh_LbrNas", jmlh_LbrNas) :
                new ObjectParameter("Jmlh_LbrNas", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pr_DiffKuotaCuti", nipParameter, dateawalParameter, dateakhirParameter, jmlh_LbrNasParameter);
        }
    
        public virtual ObjectResult<string> pr_getIDLembur()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("pr_getIDLembur");
        }
    
        public virtual ObjectResult<string> pr_getLastNIP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("pr_getLastNIP");
        }
    
        public virtual int pr_KuotaCuti(string nip)
        {
            var nipParameter = nip != null ?
                new ObjectParameter("nip", nip) :
                new ObjectParameter("nip", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_KuotaCuti", nipParameter);
        }
    
        public virtual int pr_RenewalClaim(string nip)
        {
            var nipParameter = nip != null ?
                new ObjectParameter("nip", nip) :
                new ObjectParameter("nip", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_RenewalClaim", nipParameter);
        }
    }
}
