//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOPACE_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tunjangan_medical
    {
        public string NIP { get; set; }
        public Nullable<decimal> saldo_kacamata { get; set; }
        public Nullable<decimal> saldo_rawat_jalan { get; set; }
        public Nullable<decimal> saldo_rawat_inap { get; set; }
        public Nullable<System.DateTime> renewalDate { get; set; }
        public string status { get; set; }
    
        public virtual personal_information personal_information { get; set; }
    }
}
